name: PR Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew test

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: APK Size Check
        run: |
          MAX_SIZE=5000000 # 5MB
          APK_PATH=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
          if [ -z "$APK_PATH" ]; then
            echo "Debug APK not found!"
            exit 1
          fi
          APK_SIZE=$(stat -c%s "$APK_PATH")
          echo "APK size is $APK_SIZE bytes"
          if [ "$APK_SIZE" -gt "$MAX_SIZE" ]; then
            echo "APK size exceeds 5MB limit!"
            exit 1
          fi
